<Project>
	<!-- что бы в каждый проект не добавлять -->
	<ItemGroup>
		<!-- Удаляем ВСЕ из _draft -->
		<Compile Remove="**/_draft/**"/>
		<EmbeddedResource Remove="**/_draft/**"/>
		<None Remove="**/_draft/**"/>
		<Content Remove="**/_draft/**"/>
		<!-- Удаляем ВСЕ из _experimental -->
		<Compile Remove="**/_experimental/**"/>
		<EmbeddedResource Remove="**/_experimental/**"/>
		<None Remove="**/_experimental/**"/>
		<Content Remove="**/_experimental/**"/>
	</ItemGroup>
</Project>
