<Project>
	<PropertyGroup>
		<!--<DateTime -->
		<StartYear>2014</StartYear>
		<CurrentYear>$([System.DateTime]::Now.Year)</CurrentYear>
		<!--<Version />-->
		<Deterministic>false</Deterministic>
		<AssemblyVersion>1.0.*</AssemblyVersion>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
		<GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
		<!--<Version />-->
		<!-- Description -->
		<Product>GPT Utilities</Product>
		<Company>doctorRaz</Company>
		<Authors>Разыграев Андрей</Authors>
		<Description>ChatGPT JSON to Markdown converter and Others.</Description>
		<Copyright>© Разыграев Андрей  $(StartYear)-$(CurrentYear)</Copyright>
		<Trademark>doctorRaz $(StartYear)-$(CurrentYear)</Trademark>
		<AssemblyTitle>GPT Utilities</AssemblyTitle>
		<NeutralLanguage>ru-RU</NeutralLanguage>
		<RepositoryUrl>https://github.com/doctorRaz/GPTJsonMd</RepositoryUrl>
				<!-- путь сборки в каталоге решения общий bin -->
		<BaseOutputPath>..\bin\</BaseOutputPath>
		<OutputPath>$(SolutionDir)bin\$(Configuration)</OutputPath>
	</PropertyGroup>
</Project>
