<Project Sdk="Microsoft.NET.Sdk">

	<!-- file:///D:/@Developers/%D0%92%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5/Reminder/SpecSPDS/Assemble/%D0%A3%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D1%87%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D1%84%D0%B0%D0%B9%D0%BB%D0%B0%20%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0.md -->
	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Description>Раскладывает дубликаты по соответствующим каталогам</Description>
		<HostFamily>$(MSBuildProjectName)</HostFamily>
		<HostCode>_$(MSBuildProjectName)</HostCode>
		<ApplicationIcon>Refresh.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="Refresh.ico" />
	</ItemGroup>
</Project>
