<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Description>Раскидывает json в markdown по чатам</Description>
		<HostFamily>$(MSBuildProjectName)</HostFamily>
		<HostCode>_$(MSBuildProjectName)</HostCode>
		<ApplicationIcon>Refresh.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="Refresh.ico" />
	</ItemGroup>
</Project>
